name: my_flutter_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/male_avatar.jpg
    - assets/female_avatar.jpg
    - assets/male_avatar01.jpg
    - assets/male_avatar02.png
